[template]
cargo_generate_version = ">=0.13.1"
ignore = ["LICENSE", "README.md"]

[placeholders.url]
type = "string"
prompt = "Paste Leetcode problem URL"
# \u0023 = '#'
regex = "https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~\u0023=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~\u0023?&//=]*)"
